
CREATE TABLE MANUFACTURER
(
	ID INT PRIMARY KEY NOT NULL,
	NAME TEXT,
	REGION TEXT,
	URL TEXT
);

CREATE TABLE MODEL
(
	ID INT PRIMARY KEY NOT NULL,
	MANUFACTURER_ID INT,
	NAME TEXT,
	URL TEXT
);

CREATE TABLE FRAME
(
	ID INT PRIMARY KEY NOT NULL,
	MODEL_ID INT,
	NAME TEXT,
	URL TEXT
);

CREATE TABLE COMPLECTATION
(
	ID INT PRIMARY KEY NOT NULL,
	FRAME_ID INT,
	NAME TEXT,
	URL TEXT,
	ENGINE_MNEMONIC TEXT,
	ENGINE_LABEL TEXT,
	PRODUCTION_PERIOD TEXT,
	BODY_MNEMONIC TEXT,
	BODY_LABEL TEXT,
	GRADE_MNEMONIC TEXT,
	GRADE_LABEL TEXT,
	TRANSMISSION_MNEMONIC TEXT,
	TRANSMISSION_LABEL TEXT
);

CREATE TABLE COMPLECTATION_OPTIONS
(
	COMPLECTATION_ID INT NOT NULL,
	OPTION_MNEMONIC TEXT,
	OPTION_LABEL TEXT
);
	
CREATE TABLE GROUP_PARTS
(
	ID INT PRIMARY KEY NOT NULL,
	COMPLECTATION_ID INT NOT NULL,
	CLASS TEXT,
	GROUP_NAME TEXT,
	URL TEXT
);
	
CREATE TABLE PARTS
(
	ID INT PRIMARY KEY NOT NULL,
	GROUP_PART_ID NOT NULL,
	NAME TEXT,
	URL TEXT
);

